os:
  - linux
language: perl6
perl6:
  # - latest
  - '2019.03'
install:
  - sudo apt-get install libmarkdown2-dev
  - rakudobrew build-zef
  # - zef install https://${GH_TOKEN}@github.com/risou/Lithograph.git
  - zef install Text::Markdown::Discount
  - zef install Template6
  - zef install YAMLish --force-test
  - git clone --depth 1 https://${GH_TOKEN}@github.com/risou/Lithograph.git
before_script:
  - git checkout master
script:
  - export PERL6LIB=Lithograph/lib
  # - perl6 Lithograph/bin/lithograph create
  # - perl6 Lithograph/bin/lithograph build
  - bash Lithograph/bin/build.sh
after_success:
  - git add docs/*
  - git commit -m "[ci skip] by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master # >/dev/null 2>&1
notifications:
  email: false
  slack:
    secure: oeU47PKNeHx8rVqMTTV3XIm0pqqtKgXjZ20ljF6zSrne/1cmcossIr+R37SxjlWi9MQOnkV8QvfZ0R1FHKVWUwQUl4SCi6o/e3MgcEAzoJ9yHJyJ47BaHBx+DXmqcMmO/tIq+z4P8ebh3EX6XKyMy77r6nkhMbi/h3fx5YCMcEg5xcjC2TEKzxN8q7FOu2S0Mf2PYoAT08hYIGxUy+oLT7r8AkIXJf9YZoCPu2CTUL8uE4UFS9gomA4ZmF9BMClSxQEXJtdhid5vOmc0GLGxemwKRluOCLFDKeCKsTtX0yZ646197OwDyI7qRRWkf9dwNR0Zz96BO7xKdJDdNZUkZFOQHF+J1zAuCqZcCzIF8zAp6UUAfXQlpfXfNCzvd4T0BO4+Pci5tAzZ9TLCw5i3Z1KrQxdNA7ZZ/KttIl4CD7SSAy+qS6tWzBoIDP1r9hjDhQJjYIhZYnjZbM8xlHGJwNvffX6J8dh3ShDDXswlPDLqWYnkG13J290JrNA0XH93DAKoHhvxiYKxP+V8USa9nCGDPKKdLgK2X5ETSgxv9BTnGYi4JMdBrli7c6uzJ3hcDupgwWy6BeRujWWr9C7C5U6nLUkebjhhsM50t2amCtyaphQQ7APMWmVoicTU8pH/8FJe1d/WTCnBP0ozbjNvq1ThUXZSWz88EZx3q6ON1GU=
