blog:
  title: risou's Lithograph
  footer: 'Copyright &copy; 2019- risou All Rights Reserved.'
  domain: blog.risouf.net
  description: "risou's mini blog - writing about software engineering, thinking, private events"
ogp:
  default_image: https://blog.risouf.net/static/img/sunglass.jpeg
  fb_app_id: 2945406965474658
  twitter_id: risou
  default_twitter_card: summary
option:
  ga_id: UA-29519043-1
