on:
  push:
    branches:
      - test-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: build pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        uses: Raku/setup-raku@v1
      - name: Install
        run: |
          sudo apt-get install libmarkdown2-dev
          zef install Text::Markdown::Discount
          zef install Template6
          zef install YAMLish --force-test
          git clone --depth 1 https://github.com/risou/Lithograph.git
      - name: Build
        run: |
          raku -V