on:
  push:
    branches:
      - test-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    name: build pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        uses: Raku/setup-raku@v1
      - name: Install
        run: |
          sudo apt-get install libmarkdown2-dev
          zef install Text::Markdown::Discount
          zef install Template6
          zef install YAMLish --force-test
          git clone --depth 1 https://github.com/risou/Lithograph.git
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git switch ${GITHUB_REF##*/}
          export RAKULIB=Lithograph/lib
          bash Lithograph/bin/build.sh
          git add docs/*
          git commit -m "[ci skip] by GitHub Actions (JOB $GITHUB_RUN_NUMBER)"
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git ${GITHUB_REF##*/} # >/dev/null