on:
  push:
    branches:
      - test-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: build pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        uses: Raku/setup-raku@v1
      - name: Install
        run: |
          zef install Text::Markdown::Discount
          zef install Template6
          zef install YAMLish --force-test
          zef list --installed



	  